package fr.eni.gestion_parking.bll;

/**
 * Classe BLLExceptionType
 *
 * @author lrabu
 */
public enum BLLExceptionType {
    ERROR_VOITURE_NOM_VIDE,
    ERROR_VOITURE_PLAQUE_VIDE,
    ERROR_VOITURE_PLAQUE_TAILLE,
    ERROR_VOITURE_PLAQUE_FORMAT,
    ERROR_VOITURE_PRESENTE_BASE,
    ERROR_VOITURE_NON_PRESENTE_BASE,
    ERROR_PERSONNE_PRESENTE_BASE,
    ERROR_PERSONNE_NON_PRESENTE_BASE,
    ERROR_PERSONNE_NOM_VIDE,
    ERROR_PERSONNE_PRENOM_VIDE,
    ERROR_PERSONNE_ASSOCIE_VOITURE,
    OTHER;
}
